export const mockFarmers = [
  {
    _id: 'farmer1',
    name: 'Ravi Kumar',
    email: 'ravi@farm.com',
    avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150',
    district: 'Warangal',
    state: 'Telangana',
    farming_type: 'organic',
    bio: 'Third-generation farmer growing the finest organic vegetables in Warangal district.',
    story: 'My grandfather started this farm in 1952. We have been growing vegetables with traditional methods passed down through generations. Three years ago, I switched to certified organic farming to protect our soil and provide healthier food to city families.',
    years_of_farming: 15,
    verified: true,
    total_earned: 84500,
    pending_payout: 3200,
    certifications: [{ name: 'India Organic', hash: '0xAB3F...92CD', issue_date: '2023-01-15' }],
  },
  {
    _id: 'farmer2',
    name: 'Lakshmi Devi',
    email: 'lakshmi@farm.com',
    avatar: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=150',
    district: 'Nalgonda',
    state: 'Telangana',
    farming_type: 'organic',
    bio: 'Specializing in traditional rice varieties and millets. Preserving heritage seeds.',
    story: 'I am passionate about preserving heirloom seeds. My farm grows 12 varieties of traditional rice that were nearly extinct. Every grain tells a story of our ancestors and their wisdom.',
    years_of_farming: 22,
    verified: true,
    total_earned: 125000,
    pending_payout: 8900,
    certifications: [],
  },
  {
    _id: 'farmer3',
    name: 'Suresh Reddy',
    email: 'suresh@farm.com',
    avatar: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=150',
    district: 'Karimnagar',
    state: 'Telangana',
    farming_type: 'conventional',
    bio: 'Large-scale vegetable farming with modern techniques. Reliable supply all year.',
    story: 'I run a 50-acre farm using precision agriculture. We use drip irrigation and soil testing to maximize yield while minimizing water usage. Proud to supply fresh vegetables to over 200 families every week.',
    years_of_farming: 10,
    verified: true,
    total_earned: 210000,
    pending_payout: 15000,
    certifications: [],
  },
];

export const mockProducts = [
  {
    _id: 'prod1',
    farmer_id: 'farmer1',
    farmer_name: 'Ravi Kumar',
    farmer_district: 'Warangal',
    crop_name: 'Tomatoes',
    variety: 'Desi Red',
    category: 'vegetables',
    quantity_kg: 150,
    original_quantity: 200,
    price_per_kg: 35,
    harvest_date: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
    available_until: new Date(Date.now() + 5 * 24 * 60 * 60 * 1000).toISOString(),
    storage_method: 'Cool dry place',
    organic: true,
    blockchain_hash: '0x7a3f8b2c1d4e5f6a7b8c9d0e1f2a3b4c5d6e7f8a',
    photos: [
      'https://images.unsplash.com/photo-1546470427-227c0a5e3e97?w=400',
      'https://images.unsplash.com/photo-1592924357228-91a4daadcfea?w=400',
    ],
    status: 'active',
    carbon_saved_per_kg: 0.21,
    district: 'Warangal',
  },
  {
    _id: 'prod2',
    farmer_id: 'farmer2',
    farmer_name: 'Lakshmi Devi',
    farmer_district: 'Nalgonda',
    crop_name: 'Basmati Rice',
    variety: 'Traditional Sona Masoori',
    category: 'grains',
    quantity_kg: 500,
    original_quantity: 800,
    price_per_kg: 55,
    harvest_date: new Date(Date.now() - 10 * 24 * 60 * 60 * 1000).toISOString(),
    available_until: new Date(Date.now() + 30 * 24 * 60 * 60 * 1000).toISOString(),
    storage_method: 'Airtight bags, cool place',
    organic: true,
    blockchain_hash: '0x8b4c9d2e3f1a5b6c7d8e9f0a1b2c3d4e5f6a7b8c',
    photos: [
      'https://images.unsplash.com/photo-1586201375761-83865001e31c?w=400',
    ],
    status: 'active',
    carbon_saved_per_kg: 0.21,
    district: 'Nalgonda',
  },
  {
    _id: 'prod3',
    farmer_id: 'farmer3',
    farmer_name: 'Suresh Reddy',
    farmer_district: 'Karimnagar',
    crop_name: 'Spinach',
    variety: 'Palak',
    category: 'vegetables',
    quantity_kg: 80,
    original_quantity: 100,
    price_per_kg: 28,
    harvest_date: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
    available_until: new Date(Date.now() + 3 * 24 * 60 * 60 * 1000).toISOString(),
    storage_method: 'Refrigerate',
    organic: false,
    blockchain_hash: '0x9c5d0e3f4a2b6c7d8e9f0a1b2c3d4e5f6a7b8c9d',
    photos: [
      'https://images.unsplash.com/photo-1576045057995-568f588f82fb?w=400',
    ],
    status: 'active',
    carbon_saved_per_kg: 0.21,
    district: 'Karimnagar',
  },
  {
    _id: 'prod4',
    farmer_id: 'farmer1',
    farmer_name: 'Ravi Kumar',
    farmer_district: 'Warangal',
    crop_name: 'Brinjal',
    variety: 'Purple Round',
    category: 'vegetables',
    quantity_kg: 60,
    original_quantity: 80,
    price_per_kg: 25,
    harvest_date: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000).toISOString(),
    available_until: new Date(Date.now() + 4 * 24 * 60 * 60 * 1000).toISOString(),
    storage_method: 'Cool dry place',
    organic: true,
    blockchain_hash: '0xab6e1f4a5b3c7d8e9f0a1b2c3d4e5f6a7b8c9d0e',
    photos: [
      'https://images.unsplash.com/photo-1659904604064-9d5e6f93ad05?w=400',
    ],
    status: 'active',
    carbon_saved_per_kg: 0.21,
    district: 'Warangal',
  },
  {
    _id: 'prod5',
    farmer_id: 'farmer2',
    farmer_name: 'Lakshmi Devi',
    farmer_district: 'Nalgonda',
    crop_name: 'Mango',
    variety: 'Alphonso',
    category: 'fruits',
    quantity_kg: 120,
    original_quantity: 200,
    price_per_kg: 120,
    harvest_date: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString(),
    available_until: new Date(Date.now() + 7 * 24 * 60 * 60 * 1000).toISOString(),
    storage_method: 'Room temperature or refrigerate',
    organic: true,
    blockchain_hash: '0xbc7f2a5b6c4d8e9f0a1b2c3d4e5f6a7b8c9d0e1f',
    photos: [
      'https://images.unsplash.com/photo-1571771894821-ce9b6c11b08e?w=400',
    ],
    status: 'active',
    carbon_saved_per_kg: 0.21,
    district: 'Nalgonda',
  },
  {
    _id: 'prod6',
    farmer_id: 'farmer3',
    farmer_name: 'Suresh Reddy',
    farmer_district: 'Karimnagar',
    crop_name: 'Onion',
    variety: 'Red Onion',
    category: 'vegetables',
    quantity_kg: 300,
    original_quantity: 500,
    price_per_kg: 22,
    harvest_date: new Date(Date.now() - 7 * 24 * 60 * 60 * 1000).toISOString(),
    available_until: new Date(Date.now() + 20 * 24 * 60 * 60 * 1000).toISOString(),
    storage_method: 'Cool dry place, avoid moisture',
    organic: false,
    blockchain_hash: '0xcd8a3b6c7d5e9f0a1b2c3d4e5f6a7b8c9d0e1f2a',
    photos: [
      'https://images.unsplash.com/photo-1518977676601-b53f82aba655?w=400',
    ],
    status: 'active',
    carbon_saved_per_kg: 0.21,
    district: 'Karimnagar',
  },
];

export const mockOrders = [
  {
    _id: 'order1',
    consumer_id: 'consumer1',
    consumer_name: 'Priya Sharma',
    farmer_id: 'farmer1',
    farmer_name: 'Ravi Kumar',
    product_id: 'prod1',
    product_name: 'Tomatoes',
    quantity: 5,
    total_amount: 175,
    payment_method: 'upi',
    escrow_status: 'held',
    order_status: 'out_for_delivery',
    delivery_slot: 'morning',
    created_at: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(),
    transaction_hash: '0xTXN7a3f8b2c1d4e5f6',
  },
  {
    _id: 'order2',
    consumer_id: 'consumer2',
    consumer_name: 'Amit Patel',
    farmer_id: 'farmer2',
    farmer_name: 'Lakshmi Devi',
    product_id: 'prod2',
    product_name: 'Basmati Rice',
    quantity: 10,
    total_amount: 550,
    payment_method: 'card',
    escrow_status: 'released',
    order_status: 'delivered',
    delivery_slot: 'evening',
    created_at: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000).toISOString(),
    transaction_hash: '0xTXN8b4c9d2e3f1a5b6',
  },
];

export const mockGroupBuys = [
  {
    _id: 'gb1',
    product_name: 'Alphonso Mangoes',
    farmer_name: 'Lakshmi Devi',
    image: 'https://images.unsplash.com/photo-1571771894821-ce9b6c11b08e?w=400',
    original_price: 120,
    target_qty: 200,
    current_qty: 148,
    discount_price: 90,
    deadline: new Date(Date.now() + 2 * 24 * 60 * 60 * 1000).toISOString(),
    participants: 37,
  },
  {
    _id: 'gb2',
    product_name: 'Organic Tomatoes Box',
    farmer_name: 'Ravi Kumar',
    image: 'https://images.unsplash.com/photo-1546470427-227c0a5e3e97?w=400',
    original_price: 35,
    target_qty: 500,
    current_qty: 320,
    discount_price: 25,
    deadline: new Date(Date.now() + 5 * 24 * 60 * 60 * 1000).toISOString(),
    participants: 64,
  },
];

export const mockDemandTrends = [
  { crop: 'Tomatoes', demand_change: +34, district: 'Warangal' },
  { crop: 'Leafy Greens', demand_change: +28, district: 'Hyderabad' },
  { crop: 'Mangoes', demand_change: +45, district: 'Nalgonda' },
  { crop: 'Onions', demand_change: -12, district: 'Karimnagar' },
  { crop: 'Potatoes', demand_change: +15, district: 'Warangal' },
];

export const mockSalesData = [
  { month: 'Jan', sales: 12000 },
  { month: 'Feb', sales: 18000 },
  { month: 'Mar', sales: 15000 },
  { month: 'Apr', sales: 22000 },
  { month: 'May', sales: 28000 },
  { month: 'Jun', sales: 35000 },
  { month: 'Jul', sales: 30000 },
];

export const mockEvents = [
  {
    _id: 'event1',
    title: 'Warangal Organic Farmer Market',
    date: new Date(Date.now() + 7 * 24 * 60 * 60 * 1000).toISOString(),
    location: 'Hanamkonda, Warangal',
    description: 'Weekly organic farmer market with 50+ stalls. Fresh vegetables, fruits, and handicrafts. Family friendly event with food stalls.',
    organizer: 'Ravi Kumar',
    category: 'farmer_market',
  },
  {
    _id: 'event2',
    title: 'Harvest Festival 2024',
    date: new Date(Date.now() + 14 * 24 * 60 * 60 * 1000).toISOString(),
    location: 'Nalgonda District',
    description: 'Annual harvest festival celebrating the Rabi crop season. Traditional music, food, and cultural programs.',
    organizer: 'Lakshmi Devi',
    category: 'festival',
  },
];

export const mockCommunityPosts = [
  {
    _id: 'post1',
    author: 'Ravi Kumar',
    district: 'Warangal',
    category: 'Crop Tips',
    title: 'How I improved my tomato yield by 40% using mulching',
    content: 'After struggling with water retention issues for years, I started using paddy straw mulching between rows. This reduced watering frequency by half and the moisture retention significantly improved yield...',
    likes: 47,
    replies: 12,
    created_at: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    _id: 'post2',
    author: 'Lakshmi Devi',
    district: 'Nalgonda',
    category: 'Market Prices',
    title: 'Sona Masoori rice prices expected to rise in August',
    content: 'Based on my discussions with traders at Nalgonda market, the demand for traditional rice varieties is increasing. Prices may go up 15-20% in the next month...',
    likes: 89,
    replies: 24,
    created_at: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
  },
];

export const calculateFreshnessScore = (harvestDate: string): number => {
  const daysDiff = Math.floor((Date.now() - new Date(harvestDate).getTime()) / (1000 * 60 * 60 * 24));
  return Math.max(0, 100 - (daysDiff * 8));
};

export const getFreshnessLabel = (score: number): { label: string; color: string } => {
  if (score >= 80) return { label: 'Very Fresh', color: 'green' };
  if (score >= 50) return { label: 'Fresh', color: 'amber' };
  return { label: 'Use Soon', color: 'red' };
};

export const generateBlockchainHash = (): string => {
  return '0x' + Array.from({ length: 40 }, () => Math.floor(Math.random() * 16).toString(16)).join('');
};

export const mockJourneySteps = (productId: string) => [
  {
    step: 'Seed Planted',
    date: new Date(Date.now() - 90 * 24 * 60 * 60 * 1000).toISOString(),
    location: 'Warangal, Telangana',
    actor: 'Ravi Kumar (Farmer)',
    hash: '0xA1B2...C3D4',
    completed: true,
  },
  {
    step: 'Harvested',
    date: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
    location: 'Warangal Farm, Plot 12',
    actor: 'Ravi Kumar (Farmer)',
    hash: '0xE5F6...G7H8',
    completed: true,
  },
  {
    step: 'Quality Checked',
    date: new Date(Date.now() - 1.5 * 24 * 60 * 60 * 1000).toISOString(),
    location: 'FarmConnect QC Center, Warangal',
    actor: 'FarmConnect Platform',
    hash: '0xI9J0...K1L2',
    completed: true,
  },
  {
    step: 'Packed',
    date: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
    location: 'FarmConnect Pack Center',
    actor: 'FarmConnect Platform',
    hash: '0xM3N4...O5P6',
    completed: true,
  },
  {
    step: 'Dispatched',
    date: new Date(Date.now() - 12 * 60 * 60 * 1000).toISOString(),
    location: 'Hyderabad Hub',
    actor: 'Delivery Partner',
    hash: '0xQ7R8...S9T0',
    completed: true,
  },
  {
    step: 'Delivered',
    date: null,
    location: 'Consumer Address',
    actor: 'Delivery Partner',
    hash: null,
    completed: false,
  },
];
